#
# Module manifest for module 'MyModule'
#
# Generated by: MyModuleAuthor
#
# Generated on: 5/3/2021
#

@{

RootModule = 'MyModule.psm1'

ModuleVersion = '0.0.0.1'

GUID = 'fe22351e-a8b1-411e-ae86-2531f3cc20dc'

Author = 'MyModuleAuthor'

CompanyName = 'MyModule International'

Copyright = '(c) 2021 MyModuleAuthor. All rights reserved.'

Description = 'MyModule Description'

PowerShellVersion = '5.1'

FunctionsToExport = 'Get-PublicFunction1','Get-PublicFunctionTwo'

PrivateData = @{

    PSData = @{

        Prerelease = ''

        Tags = 'Sampler','MyModule','Pipeline','CICD'

        LicenseUri = 'https://github.com/phbits/MyModule/blob/main/LICENSE'

        ProjectUri = 'https://github.com/phbits/MyModule'

        ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
